timezone: "Australia/Sydney"

default_shift:
  start: "07:00"
  end: "15:00"
  duration_hours: 8

default_requirements:
  MANAGER: 1
  BARISTA: 1
  WAITER: 1
  SANDWICH: 1

# Weekend requirements (automatically applied to all Saturdays and Sundays)
weekend_requirements:
  MANAGER: 2
  BARISTA: 1
  WAITER: 2
  SANDWICH: 1

# Date-specific overrides (for special days)
overrides:
  # Add specific date overrides here if needed
  # "2025-12-25":  # Christmas
  #   MANAGER: 3
  #   BARISTA: 2
  #   WAITER: 3

hours_caps:
  max_hours_per_week_per_employee: 40

weights:
  manager_weight: 1.0
  coffee: 1.0
  sandwich: 1.0
  speed: 0.5
  customer_service: 0.5
  fairness_penalty_per_std_above_median: 2.0  # Increased to prioritize fairness

busy_days: ["Saturday", "Sunday"]
schedule_busy_days_first: true

role_time_windows:
  BARISTA:
    weekday: {start: "07:00", end: "15:00"}
    weekend_staggered:
      - {start: "07:00", end: "12:00"}
      - {start: "11:00", end: "15:00"}
  WAITER:
    weekday: {start: "07:00", end: "15:00"}
    weekend_staggered:
      - {start: "07:00", end: "12:00"}
      - {start: "11:00", end: "15:00"}
  SANDWICH:
    weekday:
      - {start: "05:00", end: "12:00"}
    weekend:
      - {start: "05:00", end: "13:30"}
      - {start: "06:00", end: "13:30"}

# Role-based weekly hours policy and penalties
hours_policy:
  MANAGER:
    target_min: 32
    target_max: 40
    hard_cap: 40
  BARISTA:
    target_min: 16
    target_max: 40
    hard_cap: 40
  WAITER:
    target_min: 16
    target_max: 40
    hard_cap: 40
  SANDWICH:
    target_min: 16
    target_max: 32
    hard_cap: 36

hours_penalties:
  per_hour_below_target: 0.5
  per_hour_above_target: 0.75

global_hard_cap: 45

reserve_hours_for_weekend:
  BARISTA: 8
  WAITER: 4
  SANDWICH: 6

weekend_fallback:
  BARISTA:
    enabled: true
    min_required: 1
    allow_single_full_shift: true
  WAITER:
    enabled: true
    min_required: 1
    allow_single_full_shift: true


